///////////////////////////////////////////////////////////
//  Kuca.cs
//  Implementation of the Class Kuca
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:59:16 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Kuca;
namespace Kuca {
	public class Kuca {

		private int broj;
		private string grad;
		private string ulica;
		private bool zakljucana;
		public List<Uredjaj> m_Uredjaj;
		public List<Osoba> ukucan;
		public Osoba Vlasnik;

		public Kuca(){

		}

		~Kuca(){

		}

	}//end Kuca

}//end namespace Kuca