///////////////////////////////////////////////////////////
//  Osoba.cs
//  Implementation of the Class Osoba
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:59:16 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Kuca {
	public class Osoba {

		protected string ime;
		protected bool mozeOtklucati;
		protected string prezime;

		public Osoba(){

		}

		~Osoba(){

		}

	}//end Osoba

}//end namespace Kuca