///////////////////////////////////////////////////////////
//  Uredjaj.cs
//  Implementation of the Class Uredjaj
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:59:16 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Kuca {
	public abstract class Uredjaj {

		protected string ime;
		protected bool stanje;

		public Uredjaj(){

		}

		~Uredjaj(){

		}

		public virtual void PromeniStanje(){

		}

	}//end Uredjaj

}//end namespace Kuca