///////////////////////////////////////////////////////////
//  Porudzbina.cs
//  Implementation of the Class Porudzbina
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 6:13:17 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Prodavnica;
namespace Prodavnica {
	public class Porudzbina {

		private DateTime datum;
		public List<Stavka> m_Stavka;

		public Porudzbina(){

		}

		~Porudzbina(){

		}

		public DateTime Datum{
			get{
				return datum;
			}
			set{
				datum = value;
			}
		}

	}//end Porudzbina

}//end namespace Prodavnica