///////////////////////////////////////////////////////////
//  Prodavnica.cs
//  Implementation of the Class Prodavnica
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 6:13:17 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Prodavnica;
namespace Prodavnica {
	public class Prodavnica {

		private string adresa;
		private string ime;
		public List<Proizvod> m_Proizvod;
		public List<Porudzbina> m_Porudzbina;

		public Prodavnica(){

		}

		~Prodavnica(){

		}

		public string Adresa{
			get{
				return adresa;
			}
			set{
				adresa = value;
			}
		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

	}//end Prodavnica

}//end namespace Prodavnica