///////////////////////////////////////////////////////////
//  Sat.cs
//  Implementation of the Class Sat
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 6:13:17 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Prodavnica;
namespace Prodavnica {
	public class Sat : Proizvod {

		public Sat(){

		}

		~Sat(){

		}

	}//end Sat

}//end namespace Prodavnica