///////////////////////////////////////////////////////////
//  Sporet.cs
//  Implementation of the Class Sporet
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:59:16 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Kuca;
namespace Kuca {
	public class Sporet : Uredjaj {

		public Sporet(){

		}

		~Sporet(){

		}

		public override void PromeniStanje(){

		}

	}//end Sporet

}//end namespace Kuca