///////////////////////////////////////////////////////////
//  Toster.cs
//  Implementation of the Class Toster
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:59:16 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Kuca;
namespace Kuca {
	public class Toster : Uredjaj {

		public Toster(){

		}

		~Toster(){

		}

		public override void PromeniStanje(){

		}

	}//end Toster

}//end namespace Kuca