///////////////////////////////////////////////////////////
//  Fiat.cs
//  Implementation of the Class Fiat
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:44:06 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Auto;
namespace Auto {
	public class Fiat : Automobil, IInstrumentalTabla {

		public Fiat(){

		}

		~Fiat(){

		}

		public float GetBrzina(){

			return 0;
		}

		public float GetGorivo(){

			return 0;
		}

		public float GetPotrosnja(){

			return 0;
		}

		public int GetRPM(){

			return 0;
		}

		public float GetUlje(){

			return 0;
		}

		/// 
		/// <param name="stanje"></param>
		public override void upali(bool stanje){

		}

	}//end Fiat

}//end namespace Auto