///////////////////////////////////////////////////////////
//  IInstrumentalTabla.cs
//  Implementation of the Interface IInstrumentalTabla
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:44:06 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Auto {
	public interface IInstrumentalTabla  {

		float GetBrzina();

		float GetGorivo();

		float GetPotrosnja();

		int GetRPM();

		float GetUlje();
	}//end IInstrumentalTabla

}//end namespace Auto