///////////////////////////////////////////////////////////
//  Sasija.cs
//  Implementation of the Class Sasija
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:44:06 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Auto {
	public class Sasija {

		private string brojSasije;

		public Sasija(){

		}

		~Sasija(){

		}

		public string BrojSasije{
			get{
				return brojSasije;
			}
			set{
				brojSasije = value;
			}
		}

	}//end Sasija

}//end namespace Auto