///////////////////////////////////////////////////////////
//  Vlasnik.cs
//  Implementation of the Class Vlasnik
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:44:06 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Auto;
namespace Auto {
	public class Vlasnik {

		private int brVozacke;
		private string ime;
		private string prezime;
		public List<Automobil> m_Automobil;

		public Vlasnik(){

		}

		~Vlasnik(){

		}

		public int BrVozacke{
			get{
				return brVozacke;
			}
			set{
				brVozacke = value;
			}
		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public string Prezime{
			get{
				return prezime;
			}
			set{
				prezime = value;
			}
		}

	}//end Vlasnik

}//end namespace Auto