///////////////////////////////////////////////////////////
//  Organizacija.cs
//  Implementation of the Class Organizacija
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Fakultet {
	public abstract class Organizacija {

		private string naziv;

		public Organizacija(){

		}

		~Organizacija(){

		}

		public string Naziv{
			get{
				return naziv;
			}
			set{
				naziv = value;
			}
		}

	}//end Organizacija

}//end namespace Fakultet