///////////////////////////////////////////////////////////
//  Predmet.cs
//  Implementation of the Class Predmet
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class Predmet {

		private string ime;
		public Profesor m_Profesor;

		public Predmet(){

		}

		~Predmet(){

		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

	}//end Predmet

}//end namespace Fakultet