///////////////////////////////////////////////////////////
//  Student.cs
//  Implementation of the Class Student
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class Student : Osoba {

		private string indeks;
		public List<Ispit> m_Ispit;
		public List<Predmet> m_Predmet;
		public Odsek m_Odsek;

		public Student(){

		}

		~Student(){

		}

		
		public string Indeks{
			get{
				return indeks;
			}
			set{
				indeks = value;
			}
		}

		

	}//end Student

}//end namespace Fakultet