///////////////////////////////////////////////////////////
//  Porudzbina.cs
//  Implementation of the Class Porudzbina
//  Generated by Enterprise Architect
//  Created on:      11-Mar-2018 5:11:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Porudzbina {

	private DateTime datum;
	public List<Stavka> m_Stavka;

	public Porudzbina(){
        datum = DateTime.Now;
        m_Stavka = new List<Stavka>();
	}

	~Porudzbina(){

	}

	public DateTime Datum{
		get{
			return datum;
		}
		set{
			datum = value;
		}
	}

    public void dodajStavku(Stavka s)
    {
        m_Stavka.Add(s);
    }

}//end Porudzbina