///////////////////////////////////////////////////////////
//  Klijent.cs
//  Implementation of the Class Klijent
//  Generated by Enterprise Architect
//  Created on:      11-Mar-2018 5:11:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Klijent {

	private string ime;
	private string prezime;
	public List<Porudzbina> m_Porudzbina;

	public Klijent(){

	}

	~Klijent(){

	}

	public string Ime{
		get{
			return ime;
		}
		set{
			ime = value;
		}
	}

	public string Prezime{
		get{
			return prezime;
		}
		set{
			prezime = value;
		}
	}

}//end Klijent