///////////////////////////////////////////////////////////
//  Naocare.cs
//  Implementation of the Class Naocare
//  Generated by Enterprise Architect
//  Created on:      11-Mar-2018 5:11:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Naocare : Proizvod {

	public Naocare(){

	}

	~Naocare(){

	}

}//end Naocare