///////////////////////////////////////////////////////////
//  Proizvod.cs
//  Implementation of the Class Proizvod
//  Generated by Enterprise Architect
//  Created on:      11-Mar-2018 5:11:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Proizvod {

	protected double cena;
	protected string ime;

	public Proizvod(){

	}

	~Proizvod(){

	}

}//end Proizvod