///////////////////////////////////////////////////////////
//  Sat.cs
//  Implementation of the Class Sat
//  Generated by Enterprise Architect
//  Created on:      11-Mar-2018 5:11:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Sat : Proizvod {

	public Sat(){

	}

	~Sat(){

	}

}//end Sat