///////////////////////////////////////////////////////////
//  Departman.cs
//  Implementation of the Class Departman
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class Departman : Organizacija {

		public List<Odsek> m_Odsek;

		public Departman(){

		}

		~Departman(){

		}

		public override string Naziv{
			get{
				return naziv;
			}
			set{
				naziv = value;
			}
		}

	}//end Departman

}//end namespace Fakultet