///////////////////////////////////////////////////////////
//  Fakultet.cs
//  Implementation of the Class Fakultet
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class Fakultet : Organizacija {

		public List<Departman> m_Departman;

		public Fakultet(){

		}

		~Fakultet(){

		}

		public override string Naziv{
			get{
				return naziv;
			}
			set{
				naziv = value;
			}
		}

	}//end Fakultet

}//end namespace Fakultet