///////////////////////////////////////////////////////////
//  IspitniRok.cs
//  Implementation of the Class IspitniRok
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class IspitniRok {

		private string ime;
		private DateTime kraj;
		private DateTime pocetak;
		public Fakultet.Fakultet m_Fakultet;

		public IspitniRok(){

		}

		~IspitniRok(){

		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public DateTime Kraj{
			get{
				return kraj;
			}
			set{
				kraj = value;
			}
		}

		public DateTime Pocetak{
			get{
				return pocetak;
			}
			set{
				pocetak = value;
			}
		}

	}//end IspitniRok

}//end namespace Fakultet