///////////////////////////////////////////////////////////
//  Katedra.cs
//  Implementation of the Class Katedra
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class Katedra : Organizacija {

		public List<Profesor> m_Profesor;
		public List<Predmet> m_Predmet;

		public Katedra(){

		}

		~Katedra(){

		}

		public override string Naziv{
			get{
				return naziv;
			}
			set{
				naziv = value;
			}
		}

	}//end Katedra

}//end namespace Fakultet