///////////////////////////////////////////////////////////
//  Odsek.cs
//  Implementation of the Class Odsek
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class Odsek : Organizacija {

		public List<Katedra> m_Katedra;
		public List<Student> m_Student;

		public Odsek(){

		}

		~Odsek(){

		}

		public override string Naziv{
			get{
				return naziv;
			}
			set{
				naziv = value;
			}
		}

	}//end Odsek

}//end namespace Fakultet