///////////////////////////////////////////////////////////
//  Profesor.cs
//  Implementation of the Class Profesor
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Fakultet;
namespace Fakultet {
	public class Profesor : Zasposlen {

		private string brKnjizice;
		public Fakultet.Katedra m_Katedra;

		public Profesor(){

		}

		~Profesor(){

		}

		public string BrKnjizice{
			get{
				return brKnjizice;
			}
			set{
				brKnjizice = value;
			}
		}

		public override string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public override string Prezime{
			get{
				return prezime;
			}
			set{
				prezime = value;
			}
		}

	}//end Profesor

}//end namespace Fakultet