///////////////////////////////////////////////////////////
//  Zasposlen.cs
//  Implementation of the Class Zasposlen
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:26:41 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Fakultet {
	public abstract class Zasposlen {

		private string ime;
		private string prezime;

		public Zasposlen(){

		}

		~Zasposlen(){

		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public string Prezime{
			get{
				return prezime;
			}
			set{
				prezime = value;
			}
		}

	}//end Zasposlen

}//end namespace Fakultet