///////////////////////////////////////////////////////////
//  Prekidac.cs
//  Implementation of the Class Prekidac
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 4:43:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Prekidac : Provodna {

	private bool status;

	public Prekidac(){

	}

	~Prekidac(){

	}

	public bool Status{
		get{
			return status;
		}
		set{
			status = value;
		}
	}

}//end Prekidac