///////////////////////////////////////////////////////////
//  Provodna.cs
//  Implementation of the Class Provodna
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 4:43:19 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Provodna : Oprema {

	private int faznost;

	public Provodna(){

	}

	~Provodna(){

	}

	public int Faznost{
		get{
			return faznost;
		}
		set{
			faznost = value;
		}
	}

}//end Provodna
