///////////////////////////////////////////////////////////
//  Naocare.cs
//  Implementation of the Class Naocare
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 6:13:17 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Prodavnica;
namespace Prodavnica {
	public class Naocare : Proizvod {

		public Naocare(){

		}

		~Naocare(){

		}

	}//end Naocare

}//end namespace Prodavnica