///////////////////////////////////////////////////////////
//  Proizvod.cs
//  Implementation of the Class Proizvod
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 6:13:17 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Prodavnica;
namespace Prodavnica {
	public abstract class Proizvod {

		private double cena;
		private string ime;
		public List<Stavka> m_Stavka;

		public Proizvod(){

		}

		~Proizvod(){

		}

		public double Cena{
			get{
				return cena;
			}
			set{
				cena = value;
			}
		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

	}//end Proizvod

}//end namespace Prodavnica