///////////////////////////////////////////////////////////
//  Automobil.cs
//  Implementation of the Class Automobil
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:44:06 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Auto;
namespace Auto {
	public abstract class Automobil {

		public string ime;
		private bool radi;
		protected TipMotora tipMotora;
		private float ugaoVolana;
		public Auto.Vlasnik m_Vlasnik;
		public Auto.Sasija m_Sasija;
		public List<Tocak> m_Tocak;

		public Automobil(){

		}

		~Automobil(){

		}

		/// 
		/// <param name="stanje"></param>
		public virtual void upali(bool stanje){

		}

	}//end Automobil

}//end namespace Auto