///////////////////////////////////////////////////////////
//  TipMotora.cs
//  Implementation of the Enumeration TipMotora
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:44:06 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Auto {
	public enum TipMotora : int {

		BENZIN,
		DIZEL,
		GAS

	}//end TipMotora

}//end namespace Auto