///////////////////////////////////////////////////////////
//  Tocak.cs
//  Implementation of the Class Tocak
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 5:44:06 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Auto {
	public class Tocak {

		public Tocak(){

		}

		~Tocak(){

		}

	}//end Tocak

}//end namespace Auto