///////////////////////////////////////////////////////////
//  Deonica.cs
//  Implementation of the Class Deonica
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 4:43:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Deonica : Provodna {

	private int duzina;

	public Deonica(){

	}

	~Deonica(){

	}

	public int Duzina{
		get{
			return duzina;
		}
		set{
			duzina = value;
		}
	}

}//end Deonica