///////////////////////////////////////////////////////////
//  Obicna.cs
//  Implementation of the Class Obicna
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 4:43:18 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Obicna : Oprema {

	public Obicna(){

	}

	~Obicna(){

	}

}//end Obicna