///////////////////////////////////////////////////////////
//  TransformatorskaStanica.cs
//  Implementation of the Class TransformatorskaStanica
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 4:43:19 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class TransformatorskaStanica {

	public List<Fider> F;
	public List<Oprema> m_Oprema;

	public TransformatorskaStanica(){

	}

	~TransformatorskaStanica(){

	}

}//end TransformatorskaStanica