///////////////////////////////////////////////////////////
//  Transformator.cs
//  Implementation of the Class Transformator
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 4:43:19 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Transformator : Provodna {

	private int brojNamotaja;

	public Transformator(){

	}

	~Transformator(){

	}

	public int BrojNamotaja{
		get{
			return brojNamotaja;
		}
		set{
			brojNamotaja = value;
		}
	}

}//end Transformator