///////////////////////////////////////////////////////////
//  Vrste.cs
//  Implementation of the Enumeration Vrste
//  Generated by Enterprise Architect
//  Created on:      13-Mar-2018 4:43:19 PM
//  Original author: Stefan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Vrste : int {

	deonica,
	transformator,
	prekidac

}//end Vrste